// AUTOGENERATED by scripts/codegen_event_types.py
// DO NOT EDIT BY HAND — re-run the script after schema changes.
// Source: chronicler.schema.events.EventPayload
// See ck3_chronicler-w2ux for why this file exists.

export const EVENT_TYPE_LITERALS = [
  "activity_completed",
  "adventurer_ended",
  "adventurer_started",
  "alliance_broken",
  "alliance_formed",
  "artifact_acquired",
  "artifact_lost",
  "birth",
  "building_completed",
  "culture_change",
  "death",
  "decision_taken",
  "divorce",
  "dynasty_legacy_unlocked",
  "epidemic_outbreak",
  "faith_change",
  "house_change",
  "imprison",
  "marriage",
  "miscarriage",
  "nickname",
  "release",
  "title_acquired",
  "title_created",
  "title_gain",
  "title_lost",
  "title_relinquished",
  "trait_gained",
  "trait_lost",
  "travel",
  "vanilla_memory",
  "war_concluded",
  "war_declared",
  "war_joined",
  "war_left",
  "war_started",
  "war_won_attacker",
  "war_won_defender",
] as const;

export type EventTypeLiteral = (typeof EVENT_TYPE_LITERALS)[number];
