"""Emit frontend/src/api/eventTypes.generated.ts from EventPayload.

ck3_chronicler-w2ux: every event type declared in
``chronicler.schema.events.EventPayload`` should have a frontend glyph
(EventsPanel.tsx ``EVENT_GLYPHS``). Maintaining the list by hand is
how x2cc shipped — the schema grew, the FE was forgotten, 9 event
types fell through to a bare-glyph fallback for weeks.

This script extracts the ``t: Literal[...]`` discriminator value from
every member of the EventPayload union and writes a generated TS
module exporting the readonly list. The frontend's EventsPanel test
imports it and asserts each entry has a renderer.

Run manually (or via a pre-commit hook) after schema changes:

    python scripts/codegen_event_types.py
"""

from __future__ import annotations

import typing
from pathlib import Path

from chronicler.schema.events import EventPayload


def extract_event_type_literals() -> list[str]:
    """Walk EventPayload's union and pull every ``t`` Literal value."""
    # EventPayload is Annotated[Union[...], Field(...)]; first arg is the
    # union itself.
    union_args = typing.get_args(EventPayload)[0]
    members = typing.get_args(union_args)
    literals: list[str] = []
    for cls in members:
        t_annotation = cls.model_fields["t"].annotation
        # t: Literal["death"] -> Literal has a single str arg
        literal_args = typing.get_args(t_annotation)
        if not literal_args:
            raise RuntimeError(
                f"EventPayload member {cls.__name__} has no Literal[...] discriminator on field 't'"
            )
        literals.append(literal_args[0])
    return sorted(literals)


def render_typescript(literals: list[str]) -> str:
    lines = [
        "// AUTOGENERATED by scripts/codegen_event_types.py",
        "// DO NOT EDIT BY HAND — re-run the script after schema changes.",
        "// Source: chronicler.schema.events.EventPayload",
        "// See ck3_chronicler-w2ux for why this file exists.",
        "",
        "export const EVENT_TYPE_LITERALS = [",
    ]
    for lit in literals:
        lines.append(f'  "{lit}",')
    lines.append("] as const;")
    lines.append("")
    lines.append("export type EventTypeLiteral = (typeof EVENT_TYPE_LITERALS)[number];")
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    literals = extract_event_type_literals()
    out_path = (
        Path(__file__).resolve().parent.parent
        / "frontend"
        / "src"
        / "api"
        / "eventTypes.generated.ts"
    )
    out_path.write_text(render_typescript(literals), encoding="utf-8")
    print(f"wrote {len(literals)} event types to {out_path}")


if __name__ == "__main__":
    main()
