"""Regenerate .memories/README.md from each memory file's `description:` frontmatter.

Part of the init-workspace task-tracking kit. The pre-commit hook runs this so the index
can never be committed stale; safe to run by hand any time.
Cross-platform (Windows + Linux).
"""

import argparse
import re
import sys
from pathlib import Path

HEADER = [
    "# Memories index",
    "",
    "Project knowledge store: one fact per file, grep-friendly, committed and shared.",
    "Each file opens with `description:` frontmatter. This index is auto-generated by",
    "`tools/memory-index.py` (run by the pre-commit hook) -- do not hand-edit the list.",
    "",
]


def parse_description(lines):
    """Return the `description:` value from YAML frontmatter, or None."""
    if not lines or lines[0].strip() != "---":
        return None
    for line in lines[1:]:
        if line.strip() == "---":
            break
        m = re.match(r"^\s*description\s*:\s*(.*)$", line)
        if m:
            return m.group(1).strip().strip('"').strip("'")
    return None


def build_index(files):
    """Build the README.md text (trailing newline) for the sorted memory files."""
    lines = list(HEADER)
    if not files:
        lines.append("_(no memories yet -- add `.memories/<kebab-key>.md` files)_")
    else:
        for f in files:
            key = f.stem
            desc = (
                parse_description(f.read_text(encoding="utf-8").splitlines()) or "(no description)"
            )
            lines.append(f"- [{key}]({f.name}) -- {desc}")
    return "\n".join(lines) + "\n"


def main(argv=None):
    ap = argparse.ArgumentParser(description="Regenerate .memories/README.md")
    ap.add_argument("--memories-dir")
    args = ap.parse_args(argv)

    mem_dir = (
        Path(args.memories_dir)
        if args.memories_dir
        else Path(__file__).resolve().parent.parent / ".memories"
    )
    if not mem_dir.is_dir():
        print(f"Memories directory not found: {mem_dir}", file=sys.stderr)
        return 1

    files = sorted((p for p in mem_dir.glob("*.md") if p.name != "README.md"), key=lambda p: p.name)
    out = build_index(files)
    readme = mem_dir / "README.md"
    readme.write_text(out, encoding="utf-8", newline="\n")
    n = len(files)
    print(f"memory-index: {n} entr{'y' if n == 1 else 'ies'} -> {readme}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
