"""v0_1_initial_schema

Revision ID: ce15b164b63c
Revises:
Create Date: 2026-04-29 23:10:15.771315

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ce15b164b63c"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "characters",
        sa.Column("ck3_id", sa.Integer(), autoincrement=False, nullable=False),
        sa.Column("first_name", sa.String(), nullable=True),
        sa.Column("dynasty_name", sa.String(), nullable=True),
        sa.Column("house_name", sa.String(), nullable=True),
        sa.Column("birth_date", sa.String(), nullable=True),
        sa.Column("death_date", sa.String(), nullable=True),
        sa.Column("culture", sa.String(), nullable=True),
        sa.Column("faith", sa.String(), nullable=True),
        sa.Column("last_seen_event_id", sa.Integer(), nullable=True),
        sa.Column("save_snapshot_json", sa.Text(), nullable=True),
        sa.Column("relevance", sa.String(), server_default="unknown", nullable=False),
        sa.PrimaryKeyConstraint("ck3_id", name=op.f("pk_characters")),
    )
    op.create_table(
        "quarantine",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("raw_line", sa.Text(), nullable=False),
        sa.Column("error", sa.Text(), nullable=False),
        sa.Column("ts", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_quarantine")),
    )
    op.create_table(
        "schema_meta",
        sa.Column("key", sa.String(), nullable=False),
        sa.Column("value", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("key", name=op.f("pk_schema_meta")),
    )
    op.create_table(
        "events",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("schema_version", sa.Integer(), nullable=False),
        sa.Column("event_type", sa.String(), nullable=False),
        sa.Column("event_date", sa.String(), nullable=False),
        sa.Column("wall_clock_at", sa.String(), nullable=False),
        sa.Column("primary_character_id", sa.Integer(), nullable=False),
        sa.Column("payload_json", sa.Text(), nullable=False),
        sa.Column("raw_line", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["primary_character_id"],
            ["characters.ck3_id"],
            name=op.f("fk_events_primary_character_id_characters"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_events")),
        sa.UniqueConstraint(
            "event_type",
            "event_date",
            "primary_character_id",
            "payload_json",
            name="events_idempotency",
        ),
    )
    with op.batch_alter_table("events", schema=None) as batch_op:
        batch_op.create_index(
            "ix_events_char_date", ["primary_character_id", "event_date"], unique=False
        )

    op.create_table(
        "event_participants",
        sa.Column("event_id", sa.Integer(), nullable=False),
        sa.Column("character_id", sa.Integer(), nullable=False),
        sa.Column("role", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["character_id"],
            ["characters.ck3_id"],
            name=op.f("fk_event_participants_character_id_characters"),
        ),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["events.id"],
            name=op.f("fk_event_participants_event_id_events"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "event_id", "character_id", "role", name=op.f("pk_event_participants")
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("event_participants")
    with op.batch_alter_table("events", schema=None) as batch_op:
        batch_op.drop_index("ix_events_char_date")

    op.drop_table("events")
    op.drop_table("schema_meta")
    op.drop_table("quarantine")
    op.drop_table("characters")
    # ### end Alembic commands ###
